fun main() {
    print("Первое число: ")
    var a = readLine()!!.toInt()
    print("Второе число: ")
    var b = readLine()!!.toInt()
    print("Третье число: ")
    var c = readLine()!!.toInt()
    print("Четвёртое число: ")
    var d = readLine()!!.toInt()
    println("Числа в столбик: ")
    println(a)
    println(b)
    println(c)
    println(d)
}
